export const ACTIVITY_CONSTANTS = {
  LIKE_POST: "LIKE_POST",
  CREATE_POST: "CREATE_POST",
  COMMENT_POST: "COMMENT_POST",
  FOLLOW_USER: "FOLLOW_USER",
  UNFOLLOW_USER: "UNFOLLOW_USER",
  REMOVE_LIKE_POST: "REMOVE_LIKE_POST",
  REMOVE_COMMENT_POST: "REMOVE_COMMENT_POST",
  REMOVE_FOLLOW_USER: "REMOVE_FOLLOW_USER",
  UPDATE_COMMENT_POST: "UPDATE_COMMENT_POST",
  REMOVE_POST: "REMOVE_POST",
};
